name: Build

on:
  push:
    branches:
      - main

jobs:
  build_all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update local toolchain
        run: |
          rustup update stable
          rustup component add clippy
          rustup target add wasm32-wasi

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version

      - name: Run
        run: |
          curl -vL https://github.com/bytecodealliance/preview2-prototyping/releases/download/latest/wasi_snapshot_preview1.wasm --output wasi_snapshot_preview1.wasm
          cargo build --release --target wasm32-wasi -p wasm_lib
          cargo run --release