name: Build

on:
  push:
    branches:
      - main

jobs:
  build_all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update local toolchain
        run: |
          rustup update stable
          rustup component add clippy
          rustup target add wasm32-wasi

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version

      - name: Run
        run: |
          ./run.sh